intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{A}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBA_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBA_SHARED_BUILD

# Export options.
#
lib{A}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{A}: cxx.export.poptions += -DLIBA_STATIC
libs{A}: cxx.export.poptions += -DLIBA_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{A}: bin.lib.version = "-$version.project_id"
else
  lib{A}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libA/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libA/
  install.subdirs = true
}
